#!/usr/bin/env python
# SPDX-FileCopyrightText: (C) 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0
"""
Auto-generated TTSIM workload from TTIR.

This file was automatically generated by the TTIR to TTSIM converter.
It implements a TTSIM workload that matches the computational graph
defined in the original TTIR MLIR file.

Do not modify this file manually - regenerate it using the converter tool.
"""

import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))

import ttsim.front.functional.op as F
import ttsim.front.functional.sim_nn as SimNN
from ttsim.ops import SimTensor
import numpy as np
import logging

class ConvReluDemo(SimNN.Module):

    def __init__(self, name, cfg):
        super().__init__()
        self.name = name
        self.bs = cfg.get('bs', 1)

        # Operations
        self.var_0 = F._from_shape('var_0', [1, 16, 30, 30], is_param=False, is_const=False)
        self.var_1 = F.Conv2d('var_1', 3, 16, 3, stride=[1, 1], padding=[0, 0, 0, 0], dilation=[1, 1], groups=1, bias=True)
        self.var_2 = F._from_shape('var_2', [1, 16, 30, 30], is_param=False, is_const=False)
        self.var_3 = F.Add('var_3')
        self.var_4 = F._from_shape('var_4', [1, 16, 30, 30], is_param=False, is_const=False)
        self.var_5 = F.Relu('var_5')

        super().link_op2module()

    def create_input_tensors(self):
        self.input_tensors = {
            'arg0': F._from_shape('arg0', [1, 3, 32, 32], is_param=False, np_dtype=np.float16),
            'arg1': F._from_shape('arg1', [16, 3, 3, 3], is_param=False, np_dtype=np.float16),
            'arg2': F._from_shape('arg2', [16], is_param=False, np_dtype=np.float16),
        }
        return

    def __call__(self):
        t0 = self.var_0
        t1 = self.var_1(self.input_tensors['arg0'])
        t2 = self.var_2
        t3 = t1
        t4 = self.var_4
        t5 = self.var_5(t3)
        return t5

    def get_forward_graph(self):
        return super()._get_forward_graph(self.input_tensors)
    
    def analytical_param_count(self):
        # Estimate parameter count based on workload operations
        return 43648

def run_standalone(outdir: str = ".") -> None:
    # Example configuration for ConvReluDemo
    config = {
        'bs': 1,
        'name': 'forward',
    }

    model = ConvReluDemo("conv_relu_demo", config)
    model.create_input_tensors()
    output = model()
    graph = model.get_forward_graph()

    # Export to ONNX
    onnx_file = f"{outdir}/conv_relu_demo.onnx"
    graph.graph2onnx(onnx_file)

if __name__ == "__main__":
    run_standalone()