#!/usr/bin/env python
# SPDX-FileCopyrightText: (C) 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0
"""
Auto-generated TTSIM workload from TTIR.

This file was automatically generated by the TTIR to TTSIM converter.
It implements a TTSIM workload that matches the computational graph
defined in the original TTIR MLIR file.

Do not modify this file manually - regenerate it using the converter tool.
"""

import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))

import ttsim.front.functional.op as F
import ttsim.front.functional.sim_nn as SimNN
from ttsim.ops import SimTensor
import numpy as np
import logging

class linear_demo(SimNN.Module):

    def __init__(self, name, cfg):
        super().__init__()
        self.name = name
        self.bs = cfg.get('bs', 1)

        # Operations
        self.weights = F._from_shape('weights', [256, 128], is_param=False, is_const=False)
        self.result = F.MatMul('result')

        super().link_op2module()

    def create_input_tensors(self):
        self.input_tensors = {
            'input': F._from_shape('input', [1, 256], is_param=False, np_dtype=np.float32),
        }
        return

    def __call__(self):
        t0 = self.weights
        t1 = self.result(self.input_tensors['input'], t0)
        return t1

    def get_forward_graph(self):
        return super()._get_forward_graph(self.input_tensors)
    
    def analytical_param_count(self):
        # Estimate parameter count based on workload operations
        return 32768

def run_standalone(outdir: str = ".") -> None:
    # Example configuration for linear_demo
    config = {
        'bs': 1,
        'name': 'simple_linear',
    }

    model = linear_demo("linear_demo", config)
    model.create_input_tensors()
    output = model()
    graph = model.get_forward_graph()

    # Export to ONNX
    onnx_file = f"{outdir}/linear_demo.onnx"
    graph.graph2onnx(onnx_file)

if __name__ == "__main__":
    run_standalone()