#!/usr/bin/env python
# SPDX-FileCopyrightText: (C) 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0
"""
Auto-generated TTSIM workload from TTIR.

This file was automatically generated by the TTIR to TTSIM converter.
It implements a TTSIM workload that matches the computational graph
defined in the original TTIR MLIR file.

Do not modify this file manually - regenerate it using the converter tool.
"""

import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))

import ttsim.front.functional.op as F
import ttsim.front.functional.sim_nn as SimNN
from ttsim.ops import SimTensor
import numpy as np
import logging

class MlpDemo(SimNN.Module):

    def __init__(self, name, cfg):
        super().__init__()
        self.name = name
        self.bs = cfg.get('bs', 1)

        # Operations
        self.var_0 = F._from_shape('var_0', [1, 64], is_param=False, is_const=False)
        self.var_1 = F.MatMul('var_1')
        self.var_2 = F._from_shape('var_2', [1, 64], is_param=False, is_const=False)
        self.var_3 = F.Add('var_3')
        self.var_4 = F._from_shape('var_4', [1, 64], is_param=False, is_const=False)
        self.var_5 = F.Relu('var_5')
        self.var_6 = F._from_shape('var_6', [1, 32], is_param=False, is_const=False)
        self.var_7 = F.MatMul('var_7')
        self.var_8 = F._from_shape('var_8', [1, 32], is_param=False, is_const=False)
        self.var_9 = F.Add('var_9')

        super().link_op2module()

    def create_input_tensors(self):
        self.input_tensors = {
            'arg0': F._from_shape('arg0', [1, 128], is_param=False, np_dtype=np.float16),
            'arg1': F._from_shape('arg1', [128, 64], is_param=False, np_dtype=np.float16),
            'arg2': F._from_shape('arg2', [64], is_param=False, np_dtype=np.float16),
            'arg3': F._from_shape('arg3', [64, 32], is_param=False, np_dtype=np.float16),
            'arg4': F._from_shape('arg4', [32], is_param=False, np_dtype=np.float16),
        }
        return

    def __call__(self):
        t0 = self.var_0
        t1 = self.var_1(self.input_tensors['arg0'], self.input_tensors['arg1'])
        t2 = self.var_2
        t3 = self.var_3(t1, self.input_tensors['arg2'])
        t4 = self.var_4
        t5 = self.var_5(t3)
        t6 = self.var_6
        t7 = self.var_7(t5, self.input_tensors['arg3'])
        t8 = self.var_8
        t9 = self.var_9(t7, self.input_tensors['arg4'])
        return t9

    def get_forward_graph(self):
        return super()._get_forward_graph(self.input_tensors)
    
    def analytical_param_count(self):
        # Estimate parameter count based on workload operations
        return 256

def run_standalone(outdir: str = ".") -> None:
    # Example configuration for MlpDemo
    config = {
        'bs': 1,
        'name': 'forward',
    }

    model = MlpDemo("mlp_demo", config)
    model.create_input_tensors()
    output = model()
    graph = model.get_forward_graph()

    # Export to ONNX
    onnx_file = f"{outdir}/mlp_demo.onnx"
    graph.graph2onnx(onnx_file)

if __name__ == "__main__":
    run_standalone()